language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: travisci+nx-logger-debug@raynode.de
node_js:
  - '8'
before_script:
  - npm install --no-save @raynode/nx-logger
  - npm run build
  - npm prune
after_success:
  - npm run coveralls
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
